### ISSUE TITLE
Does not currently work

### ISSUE THREAD

**Issue by ForsakenKLR** [ForzaMods/AIOinfo#1]
Doesn't even try to link after the new Forza update

**Comment by L0v3craft** [comment]
It doesn't open here. I have windows 10 x64 Pro 21H2 build 19044.2728.

I have installed also:
.NET 7.0 Desktop Runtime (v7.0.4)
.NET 7.0 Runtime (v7.0.4)
ASP.NET Core 7.0 Runtime (v7.0.4)

If I try to run it after that I started the game, the game crashes suddenly.
